database:
    url: "postgres://postgres:123456@localhost:5432/soybean-admin-rust-backend"
    max_connections: 10
    min_connections: 1
    connect_timeout: 30
    idle_timeout: 600
server:
    host: "127.0.0.1"
    port: 10001
jwt:
    jwt_secret: "soybean-admin-rust"
    issuer: "https://github.com/ByteByteBrew/soybean-admin-rust"
    expire: 7200
redis:
    mode: single
    url: "redis://:123456@localhost:6379/10"
mongo:
    uri: "mongodb://localhost:27017"
s3:
    region: "oss-cn-beijing"
    access_key_id: "x"
    secret_access_key: "x"
    endpoint: "https://oss-cn-beijing.aliyuncs.com"
