//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Deserialize, Serialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "\"MenuType\"")]
pub enum MenuType {
    #[sea_orm(string_value = "directory")]
    #[serde(rename = "directory")]
    Directory,
    #[sea_orm(string_value = "menu")]
    #[serde(rename = "menu")]
    Menu,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Deserialize, Serialize)]
// TODO pg大小写敏感会存在问题clear
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "\"Status\"")]
pub enum Status {
    #[sea_orm(string_value = "BANNED")]
    BANNED,
    #[sea_orm(string_value = "DISABLED")]
    DISABLED,
    #[sea_orm(string_value = "ENABLED")]
    ENABLED,
}
